# File: backend/ai-server/app/models/response_formatter.py

from datetime import datetime
from typing import Dict, Any

class ResponseFormatter:
    """
    Format and standardize AI-generated responses for consistent frontend delivery.
    """

    def __init__(self):
        self.default_disclaimer = (
            "⚠️ This response is generated by AI for informational purposes only. "
            "Please consult a qualified healthcare professional for medical advice."
        )

    def format_response(
        self,
        raw_response: str,
        model: str = "meditron",
        confidence: float = 0.85,
        language: str = "en"
    ) -> Dict[str, Any]:
        """
        Format the raw response from the AI model.

        Parameters:
        - raw_response (str): The original message from the AI model.
        - model (str): Name of the AI model used.
        - confidence (float): Confidence score.
        - language (str): Language of the response.

        Returns:
        - dict: A standardized response dictionary.
        """
        return {
            "message": self._clean_text(raw_response),
            "confidence": round(confidence, 2),
            "model": model,
            "timestamp": datetime.utcnow().isoformat(),
            "disclaimer": self.get_disclaimer(language),
            "language": language,
            "formatted": True,
            "medical_grade": True
        }

    def get_disclaimer(self, language: str = "en") -> str:
        """
        Get a language-specific disclaimer.

        Parameters:
        - language (str): ISO code for language.

        Returns:
        - str: Disclaimer message.
        """
        # Future: Add multilingual support
        return self.default_disclaimer

    def _clean_text(self, text: str) -> str:
        """
        Clean and sanitize response content.

        Parameters:
        - text (str): Raw AI response.

        Returns:
        - str: Cleaned text.
        """
        return text.strip().replace('\n\n', '\n').replace('\t', ' ').strip()
