# Flask AI Dockerfile
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY backend/ai-server/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ai-server/ .

EXPOSE 8000

CMD ["python", "run.py"]
